config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  resources :patients
  resources :dashboard, only: [:index]
  devise_for :users, controllers: {
    confirmations: 'confirmations'
  }
  root 'patients#index'
  resources :home, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
  belongs_to :patient
end

app/models/patient.rb
class Patient < ApplicationRecord
  validates :age, inclusion: 1...60
  validates :name, length: { minimum:2 }
  validates :email, format: { with: /.*@.*/ }
  validates :details, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :patients, dependent: :destroy
  has_many :meetings, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

   def username
     return self.email.split('@')[0].capitalize
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  private
    def after_confirmation_path_for(resource_name, resource)
      sign_in(resource)
        patients_path    	
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!
  def index
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    if current_user.admin
      @meetings = Meeting.all
    else
      @meetings = current_user.meetings.all
    end
    @meeting = Meeting.new
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.user_id = current_user.id
    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
        DocpatientMailer.editmailer(@meeting.patient, 'Doctor has scheduled your appointment', 'DocSite - Your appointment has been scheduled').deliver
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
        DocpatientMailer.editmailer(@meeting.patient, 'Doctor has re-scheduled your appointment', 'DocSite - Your appointment has been re-scheduled').deliver
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
      DocpatientMailer.editmailer(@meeting.patient, 'Doctor has cancelled your appointment', 'DocSite - Your appointment has been cancelled').deliver
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time, :end_time, :user_id, :patient_id)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    if current_user.admin
      @patients = Patient.all
    else
      @patients = Patient.where(user_id: current_user.id)
    end
    @patient = Patient.new
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)
    @patient.user = current_user
    respond_to do |format|
      if @patient.save
        format.html { redirect_to patients_url, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
        DocpatientMailer.editmailer(@patient, 'You have been registered to DocSite', 'Welcome to Docsite!').deliver
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        DocpatientMailer.editmailer(@patient, 'Your details with the DocSite are updated.', 'DocSite - Patient Details updated').deliver
        format.html { redirect_to patients_url, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    DocpatientMailer.editmailer(@patient, 'Your details have been removed from DocSite', 'Docsite - Patient details removed').deliver
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:name, :age, :details, :email, :appointment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def readable_time(time)
		time.strftime("%b %d, %I:%M%P")
	end
	def author_of(record)
		user_signed_in? && current_user.id == record.user_id	
	end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DocSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <%= render 'layouts/alerts' %>
    <% if current_user %>
      <%= link_to 'Appointments Schedule', meetings_path %>
      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign up', new_user_registration_path %>
      <%= link_to 'Sign In', new_user_session_path %>
    <% end %>
    <%= yield %>

  </body>
</html>

app/views/meetings/_form.html.erb
<%= form_with(model: meeting, local: true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="field">
    <%= form.label :patient_id %>
    <%= form.text_field :patient_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %> 

app/views/meetings/index.html.erb
<div class="grid-container">
<div class="item1">
<h1>Meetings</h1>

<%= month_calendar events: @meetings do |date, meetings| %>
  <%= date %>
  <% meetings.each do |meeting| %>
    <div>
      <%= link_to meeting.name, meeting %>
    </div>
  <% end %>
<% end %>

<!-- <table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start time</th>
      <th>End time</th>
      <th>User</th>
      <th>Patient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.name %></td>
        <td><%= meeting.start_time %></td>
        <td><%= meeting.end_time %></td>
        <td><%= meeting.user.username %></td>
        <td><%= meeting.patient.name %></td>
        <td><%= link_to 'Show', meeting %></td>
        <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 -->
<br>
</div>
<div class="item2">
<h1>New Meeting</h1>
<%= render 'form', meeting: @meeting %>
<%= link_to 'Back', meetings_path %>
</div>
</div>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @meeting.end_time %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @meeting.patient.name %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %> |
<%= link_to 'Destroy', @meeting, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_area :details %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :appointment %>
    <%= form.datetime_select :appointment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<div class="grid-container">
<div class="item1">
<h1>Patients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Details</th>
      <th>Email</th>
      <th>Appointment</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= patient.age %></td>
        <td><%= patient.details %></td>
        <td><%= patient.email %></td>
        <td><%= patient.appointment %></td>
        <td><%= patient.user.username %></td>
        <% if current_user %>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <% end %>
        <% if current_user && current_user.admin %>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
</div>
<div class="item2">
<h1>New Patient</h1>
<%= render 'form', patient: @patient %>
</div>
</div>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @patient.age %>
</p>

<p>
  <strong>Details:</strong>
  <%= @patient.details %>
</p>

<p>
  <strong>Email:</strong>
  <%= @patient.email %>
</p>

<p>
  <strong>Appointment:</strong>
  <%= @patient.appointment %>
</p>

<p>
  <strong>User:</strong>
  <%= @patient.user.username %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>